services:
  - type: web
    name: ezpark-platform-final
    env: java
    plan: free
    buildCommand: |
      curl -s https://get.sdkman.io | bash
      source ~/.sdkman/bin/sdkman-init.sh
      sdk install java 21.0.1-tem
      sdk install maven 3.9.6
      sdk use java 21.0.1-tem
      sdk default java 21.0.1-tem
      mvn clean package -DskipTests
    startCommand: source ~/.sdkman/bin/sdkman-init.sh && sdk use java 21.0.1-tem && java -Dserver.port=$PORT -Xmx512m -Dspring.profiles.active=gcp -jar target/ezpark-platform-0.0.1-SNAPSHOT.jar
    healthCheckPath: /api/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: gcp
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: jdbc:postgresql://34.61.141.252:5432/ezpark_platform
      - key: DB_USERNAME
        value: ezpark_user
      - key: DB_PASSWORD
        value: ")oa]mVy@%rd6\\$[*"
