services:
  - type: web
    name: ezpark-platform-final
    env: node
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: chmod +x run.sh && ./run.sh
    healthCheckPath: /api/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: gcp
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: jdbc:postgresql://34.61.141.252:5432/ezpark_platform
      - key: DB_USERNAME
        value: ezpark_user
      - key: DB_PASSWORD
        value: ")oa]mVy@%rd6\\$[*"
