services:
  - type: web
    name: ezpark-platform
    env: java
    plan: free
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/ezpark-platform-*.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: gcp
      - key: PORT
        value: 10000
